routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'auth.login');

Auth::routes(['register' => false]);

Route::get('home', 'HomeController@index')->name('home');

Route::resource('users', 'UsersController');

Route::resource('entreprises', 'EntreprisesController');

Route::resource('offres', 'OffresController');
Route::post('offres/download/{offre}', 'OffresController@download')->name('offres.download');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'is_admin', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use \App\Models\User;

class UsersController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('admin')->except(['show','edit','update']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();

        return view('users.indexUsers', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('users.createUser');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|email|unique:users|max:255',
            'password' => 'required|string|min:8|confirmed',
            'is_admin' => 'required|boolean',
        ]);

        User::create($validatedData);

        return redirect()->route('users.index')->withToastSuccess('Utilisateur créé avec succès !!');
    
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('users.profilUser', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('users.editUser', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $validatedData = $request->validate([
            'name' => 'required|string|max:255',
            'email' => 'required|email|unique:users,id,'.$user->id.'|max:255',
            'password' => 'required|string|min:8|confirmed',
            'is_admin' => 'required|boolean',
        ]);

        $user->update($validatedData);

        if (\Auth::user()->id == $user->id)
        {
            return redirect()->route('users.show', $user)->withToastSuccess('Profil mis à jour avec succès!!');
        }
        else
        {
            return redirect()->route('users.index')->withToastSuccess('Utilisateur modifié avec succès !!');
        }
        

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();
        
        return redirect()->route('users.index')->withToastSuccess('Utilisateur supprimé avec succès !!');
    }
}

resources/views/users/createUser.blade.php
@extends('layouts.template')
@section('title_page', 'Créer un utilisateur')
@section('content')

<div class="card card-primary">
    <div class="card-header">
      <h3 class="card-title">Créer un utilisateur</h3>
    </div>
    <form method="POST" action="{{route('users.store') }}">
        @csrf
        @method('POST')
      <div class="card-body">
          <div class="row">
              <div class="col-sm-6">
                <div class="form-group">
                    <label for="name">Nom et prénom</label>
                    <input type="text" class="form-control @error('name') is-invalid @enderror" id="name" name="name" placeholder="Entrer un nom et un prénom..." value="{{ old('name') }}">
                    @error('name')
                        <span id="name-error" class="error invalid-feedback">{{$errors->first('name')}}</span>
                    @enderror
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                    <label for="email">Addresse Email </label>
                    <input type="email" class="form-control @error('email') is-invalid @enderror" id="email" name="email" placeholder="Entrer une adresse mail..." value="{{ old('email') }}">
                    @error('email')
                        <span id="name-error" class="error invalid-feedback">{{$errors->first('email')}}</span>
                    @enderror
                </div>
              </div>
          </div>
          <div class="row">
            <div class="col-sm-6">
                <div class="form-group">
                    <label for="password">Mot de passe</label>
                    <input type="password" class="form-control @error('password') is-invalid @enderror" id="password" name="password" placeholder="Entrer un mot de passe...">
                    @error('password')
                        <span id="name-error" class="error invalid-feedback">{{$errors->first('password')}}</span>
                    @enderror
                </div>
            </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="password_confirmation">Confirmation du mot de passe</label>
                        <input type="password" class="form-control @error('password') is-invalid @enderror" id="password_confirmation" name="password_confirmation" placeholder="Entrer a nouveau le mot de passe...">
                    </div>
                </div>
        </div>
        <div class="row">
          <div class="col-sm-6" style="margin: auto;">
            <div class="form-group">
              <label for="is_admin">Slectionner un rôle</label>
              <select class="form-control" id="is_admin" name="is_admin">
                <option value="0">Utilisateur</option>
                <option value="1">Administrateur</option>
              </select>
            </div>
          </div>
        </div>
      </div>
      <div class="card-footer">
        <button type="submit" class="btn btn-primary">Créer l'utilisateur</button>
      </div>
    </form>
    </div>

@endsection

resources/views/users/editUser.blade.php
@extends('layouts.template')
@if (Auth::user() == $user) @section('title_page', 'Mettre à jour mon profil') @else @section('title_page', 'Mise à jour de l\'utilisateur '.$user->name) @endif
@section('content')

<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title">@if (Auth::user() == $user) Modifier mon profil @else Modifier l'utilisateur {{$user->name}} @endif</h3>
    </div>
    <form method="POST" action="{{ route('users.update', $user) }}">
        @csrf
        @method('PATCH')
      <div class="card-body">
          <div class="row">
              <div class="col-sm-6">
                <div class="form-group">
                    <label for="name">Nom et prénom</label>
                    <input type="text" class="form-control @error('name') is-invalid @enderror" id="name" name="name" placeholder="Entrer un nom et un prénom..." value="@if (old('name')) {{old('name')}}@else {{$user->name}}@endif">
                    @error('name')
                        <span id="name-error" class="error invalid-feedback">{{$errors->first('name')}}</span>
                    @enderror
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                    <label for="email">Addresse Email </label>
                    <input type="email" class="form-control @error('email') is-invalid @enderror" id="email" name="email" placeholder="Entrer une adresse mail..." value="@if (old('email')) {{old('email')}}@else {{$user->email}}@endif">
                    @error('email')
                        <span id="name-error" class="error invalid-feedback">{{$errors->first('email')}}</span>
                    @enderror
                </div>
              </div>
          </div>
          <div class="row">
            <div class="col-sm-6">
                <div class="form-group">
                    <label for="password">Mot de passe</label>
                    <input type="password" class="form-control @error('password') is-invalid @enderror" id="password" name="password" placeholder="Entrer un mot de passe...">
                    @error('password')
                        <span id="name-error" class="error invalid-feedback">{{$errors->first('password')}}</span>
                    @enderror
                </div>
            </div>
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="password_confirmation">Confirmation du mot de passe</label>
                        <input type="password" class="form-control @error('password') is-invalid @enderror" id="password_confirmation" name="password_confirmation" placeholder="Entrer a nouveau le mot de passe...">
                    </div>
                </div>
        </div>
        @if (Auth::user()->is_admin == true)
        <div class="row">
            <div class="col-sm-6" style="margin: auto;">
              <div class="form-group">
                <label for="is_admin">Slectionner un rôle</label>
                <select class="form-control" id="is_admin" name="is_admin">
                  <option value="0" @if ($user->is_admin == false) selected @endif>Utilisateur</option>
                  <option value="1" @if ($user->is_admin == true) selected @endif>Administrateur</option>
                </select>
              </div>
            </div>
          </div>
        </div>
        @endif
      <div class="card-footer">
        <button type="submit" class="btn btn-primary">@if (Auth::user() == $user) Mettre à jour mon profil @else Mettre à jour l'utilisateur @endif</button>
      </div>
    </div>
    </form>
    </div>

@endsection

resources/views/users/indexUsers.blade.php
@extends('layouts.template')
@section('title_page', 'Utilisateurs')
@section('content')
      <div class="card card-pink">
        <div class="card-header">
          <h3 class="card-title">Liste des utilisateurs</h3>
        </div>
        <div class="card-body">
            <table id="table" class="table table-bordered table-hover dataTable" role="grid">
            <thead>
                <tr role="row">
                    <th class="sorting_asc" tabindex="0" aria-controls="table" rowspan="1" colspan="1">Nom et prénom</th>
                    <th class="sorting" tabindex="0" aria-controls="table" rowspan="1" colspan="1">Adresse Email</th>
                    <th class="sorting" tabindex="0" aria-controls="table" rowspan="1" colspan="1">Rôle</th>
                    <th class="sorting" tabindex="0" aria-controls="table" rowspan="1" colspan="1" style="text-align: right">Action</th>
                </tr>
            </thead>
            <tbody>
            @foreach ($users as $user)
                <tr role="row" class="odd">                
                    <td>{{$user->name}}</td>
                    <td>{{$user->email}}</td>
                    <td>@if ($user->is_admin == true) Administrateur @elseif ($user->is_admin == false) Utilisateur @endif</td>
                    <td>
                        <div class="btn-group" style="display: block;text-align: right;">
                            <a href="{{route('users.edit', $user)}}"><button type="button" class="btn btn-primary"><i class="fas fa-edit"></i></button></a>
                        <button class="btn btn-danger remove-user" data-name="{{$user->name}}" data-action="{{ route('users.destroy',$user) }}"><i class="fas fa-trash"></i></button>
                        </div>
                    </td>
                </tr>
            @endforeach
            </tbody>
          </table>
        </div>
      </div>
      @section('script')

      <script>
$("body").on("click",".remove-user",function(){

var current_object = $(this);
var name = current_object.attr('data-name');

swal.fire({

    title: "Êtes vous sur ?",
    text: "Voulez-vous vraiment supprimer l'utilisateur suivant : "+name+" ?",
    type: 'warning',
    showCancelButton: true,
    cancelButtonColor: '#6c757d',
    confirmButtonColor: '#dc3545',
    confirmButtonText: 'Supprimer !',
    reverseButtons: true

}).then((result) =>{

    if (result.value) {

        var action = current_object.attr('data-action');

        $('body').html("<form class='form-inline remove-form' method='post' action='"+action+"'></form>");
        $('body').find('.remove-form').append('@csrf');
        $('body').find('.remove-form').append('@method('DELETE')');
        $('body').find('.remove-form').submit();
    }

});

});

      </script>
          
      @endsection

@endsection

resources/views/users/profilUser.blade.php
@extends('layouts.template')
@section('title_page', 'Mon profile')
@section('content')

<div class="card card-primary card-outline">
    <div class="card-body box-profile">
      <div class="text-center">
        <img class="profile-user-img img-fluid img-circle" src="{{asset('assets/img/avatar5.png') }}" alt="User profile picture">
      </div>

      <h3 class="profile-username text-center">{{ $user->name }}</h3>

      <p class="text-muted text-center">{{ $user->email }}</p>

      <div class="row">
        <div class="col-md-3 col-sm-6 col-12">
          <div class="info-box">
            <span class="info-box-icon bg-info"><i class="far fa-envelope"></i></span>

            <div class="info-box-content">
              <span class="info-box-text">Email </span>
              <span class="info-box-number">{{$user->email}}</span>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>
        <!-- /.col -->
        <div class="col-md-3 col-sm-6 col-12">
          <div class="info-box">
            <span class="info-box-icon bg-success"><i class="far fa-flag"></i></span>

            <div class="info-box-content">
              <span class="info-box-text">Nom et prénom</span>
              <span class="info-box-number">{{$user->name}}</span>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>
        <!-- /.col -->
        <div class="col-md-3 col-sm-6 col-12">
          <div class="info-box">
            <span class="info-box-icon bg-warning"><i class="far fa-copy"></i></span>

            <div class="info-box-content">
              <span class="info-box-text">Uploads</span>
              <span class="info-box-number">13,648</span>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>
        <!-- /.col -->
        <div class="col-md-3 col-sm-6 col-12">
          <div class="info-box">
            <span class="info-box-icon bg-danger"><i class="far fa-star"></i></span>

            <div class="info-box-content">
              <span class="info-box-text">Likes</span>
              <span class="info-box-number">93,139</span>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>
        <!-- /.col -->
      </div>

        <a href="{{ route('users.edit', $user) }}" class="btn btn-primary btn-block"><b>Mettre à jour mon profil</b></a>
    </div>
    <!-- /.card-body -->
  </div>


@endsection