routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'auth.login');

Auth::routes(['register' => false]);

Route::get('home', 'HomeController@index')->name('home');

Route::resource('users', 'UsersController');

Route::resource('entreprises', 'EntreprisesController');

Route::resource('offres', 'OffresController');
Route::post('offres/download/{offre}', 'OffresController@download')->name('offres.download');

app/Http/Controllers/EntreprisesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use \App\Models\Entreprise;

class EntreprisesController extends Controller
{

    public function __construct()
    {
        $this->middleware(['auth', 'admin']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $entreprises = Entreprise::all();

        return view('entreprises.indexEntreprise', compact('entreprises'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('entreprises.createEntreprise');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Entreprise::create($this->validateData());

        return redirect()->route('entreprises.index')->withToastSuccess('Entreprise créée avec succès !!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Entreprise $entreprise)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Entreprise $entreprise)
    {
        return view('entreprises.editEntreprise', compact('entreprise'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Entreprise $entreprise)
    {
        $entreprise->update($this->validateData());

        return redirect()->route('entreprises.index')->withToastSuccess('Entreprise modifiée avec succès !!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Entreprise $entreprise)
    {
        $entreprise->delete();

        return redirect()->route('entreprises.index')->withToastSuccess('Entreprise supprimée avec succès !!');
    }

    private function validateData()
    {
        return \Validator::make(request()->all(), [
                'nom' => 'required|string|max:255',
                'email' => 'required|email|max:255',
                'addresse' => 'required|string|max:255',
                'code_postal' => 'required|integer|digits:5',
                'ville' => 'required|string|max:255',
                'contact' => 'required|string|max:255',
                'telephone' => 'required|string|size:14',
            ])->validate();
    }
}

resources/views/entreprises/createEntreprise.blade.php
@extends('layouts.template')
@section('title_page', 'Créer une entreprise')
@section('content')

<div class="card card-primary">
    <div class="card-header">
      <h3 class="card-title">Créer une entreprise</h3>
    </div>
    <form method="POST" action="{{route('entreprises.store') }}">
        @csrf
        @method('POST')
      <div class="card-body">
          <div class="row">
              <div class="col-sm-6">
                <div class="form-group">
                    <label for="nom">Nom de l'entreprise</label>
                    <input type="text" class="form-control @error('nom') is-invalid @enderror" id="nom" name="nom" placeholder="Entrer un nom pour l'entreprise..." value="{{ old('nom') }}">
                    @error('nom')
                        <span id="name-error" class="error invalid-feedback">{{$errors->first('nom')}}</span>
                    @enderror
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                    <label for="email">Addresse Email </label>
                    <input type="email" class="form-control @error('email') is-invalid @enderror" id="email" name="email" placeholder="Entrer une adresse mail..." value="{{ old('email') }}">
                    @error('email')
                        <span id="name-error" class="error invalid-feedback">{{$errors->first('email')}}</span>
                    @enderror
                </div>
              </div>
          </div>
          <div class="row">
            <div class="col-sm-6">
                <div class="form-group">
                    <label for="addresse">Addresse</label>
                    <input type="text" class="form-control @error('addresse') is-invalid @enderror" id="addresse" name="addresse" placeholder="Entrer une addresse..." value="{{ old('addresse') }}">
                    @error('addresse')
                        <span id="name-error" class="error invalid-feedback">{{$errors->first('addresse')}}</span>
                    @enderror
                </div>
            </div>
            <div class="col-sm-3">
                <div class="form-group">
                    <label for="code_postal">Code postale</label>
                    <input type="text" class="form-control @error('code_postal') is-invalid @enderror" id="code_postal" name="code_postal" placeholder="Entrer un code postale ..." value="{{ old('code_postal') }} " data-inputmask="'mask': '99999'">
                    @error('code_postal')
                     <span id="name-error" class="error invalid-feedback">{{$errors->first('code_postal')}}</span>
                    @enderror
                </div>
            </div>
                <div class="col-sm-3">
                    <div class="form-group">
                        <label for="ville">Ville</label>
                        <input type="text" class="form-control @error('ville') is-invalid @enderror" id="ville" name="ville" placeholder="Entrer une ville..." value="{{ old('ville') }}">
                        @error('ville')
                            <span id="name-error" class="error invalid-feedback">{{$errors->first('ville')}}</span>
                        @enderror
                    </div>
                </div>

        </div>
        <div class="row">
            <div class="col-sm-6">
              <div class="form-group">
                  <label for="contact">Contact</label>
                  <input type="text" class="form-control @error('contact') is-invalid @enderror" id="contact" name="contact" placeholder="Entrer un nom et un prénom..." value="{{ old('contact') }}">
                  @error('contact')
                      <span id="name-error" class="error invalid-feedback">{{$errors->first('contact')}}</span>
                  @enderror
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group">
                  <label for="telephone">Téléphone </label>
                  <input type="text" class="form-control @error('telephone') is-invalid @enderror" id="telephone" name="telephone" placeholder="Entrer un numéro de téléphone" value="{{ old('telephone') }}" data-inputmask="'mask': '99-99-99-99-99'">
                  @error('telephone')
                      <span id="name-error" class="error invalid-feedback">{{$errors->first('telephone')}}</span>
                  @enderror
              </div>
            </div>
        </div>
      </div>
      <div class="card-footer">
        <button type="submit" class="btn btn-primary">Créer l'entreprise</button>
      </div>
    </form>
    </div>

    @section('script')

    <script>

        $("#telephone").inputmask({"mask": "99-99-99-99-99"});
        $("#code_postal").inputmask({"mask": "99999"});

    </script>


    @endsection

@endsection

resources/views/entreprises/editEntreprise.blade.php
@extends('layouts.template')
@section('title_page', 'Modifier une entreprise')
@section('content')

<div class="card card-primary">
    <div class="card-header">
      <h3 class="card-title">Modifier une entreprise</h3>
    </div>
    <form method="POST" action="{{ route('entreprises.update', $entreprise) }}">
        @csrf
        @method('PATCH')
      <div class="card-body">
          <div class="row">
              <div class="col-sm-6">
                <div class="form-group">
                    <label for="nom">Nom de l'entreprise</label>
                    <input type="text" class="form-control @error('nom') is-invalid @enderror" id="nom" name="nom" placeholder="Entrer un nom pour l'entreprise..." value="@if (old('nom')) {{ old('nom') }} @else {{$entreprise->nom}} @endif">
                    @error('nom')
                        <span id="name-error" class="error invalid-feedback">{{$errors->first('nom')}}</span>
                    @enderror
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                    <label for="email">Addresse Email </label>
                    <input type="email" class="form-control @error('email') is-invalid @enderror" id="email" name="email" placeholder="Entrer une adresse mail..." value="@if (old('email')) {{ old('email') }} @else {{$entreprise->email}} @endif">
                    @error('email')
                        <span id="name-error" class="error invalid-feedback">{{$errors->first('email')}}</span>
                    @enderror
                </div>
              </div>
          </div>
          <div class="row">
            <div class="col-sm-6">
                <div class="form-group">
                    <label for="addresse">Addresse</label>
                    <input type="text" class="form-control @error('addresse') is-invalid @enderror" id="addresse" name="addresse" placeholder="Entrer une addresse..." value="@if (old('addresse')) {{ old('addresse') }} @else {{$entreprise->addresse}} @endif">
                    @error('addresse')
                        <span id="name-error" class="error invalid-feedback">{{$errors->first('addresse')}}</span>
                    @enderror
                </div>
            </div>
            <div class="col-sm-3">
                <div class="form-group">
                    <label for="code_postal">Code postale</label>
                    <input type="text" class="form-control @error('code_postal') is-invalid @enderror" id="code_postal" name="code_postal" placeholder="Entrer un code postale ..." value="@if (old('code_postal')) {{ old('code_postal') }} @else {{$entreprise->code_postal}} @endif " data-inputmask="'mask': '99999'">
                    @error('code_postal')
                     <span id="name-error" class="error invalid-feedback">{{$errors->first('code_postal')}}</span>
                    @enderror
                </div>
            </div>
                <div class="col-sm-3">
                    <div class="form-group">
                        <label for="ville">Ville</label>
                        <input type="text" class="form-control @error('ville') is-invalid @enderror" id="ville" name="ville" placeholder="Entrer une ville..." value="@if (old('ville')) {{ old('ville') }} @else {{$entreprise->ville}} @endif">
                        @error('ville')
                            <span id="name-error" class="error invalid-feedback">{{$errors->first('ville')}}</span>
                        @enderror
                    </div>
                </div>

        </div>
        <div class="row">
            <div class="col-sm-6">
              <div class="form-group">
                  <label for="contact">Contact</label>
                  <input type="text" class="form-control @error('contact') is-invalid @enderror" id="contact" name="contact" placeholder="Entrer un nom et un prénom..." value="@if (old('contact')) {{ old('contact') }} @else {{$entreprise->contact}} @endif">
                  @error('contact')
                      <span id="name-error" class="error invalid-feedback">{{$errors->first('contact')}}</span>
                  @enderror
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group">
                  <label for="telephone">Téléphone </label>
                  <input type="text" class="form-control @error('telephone') is-invalid @enderror" id="telephone" name="telephone" placeholder="Entrer un numéro de téléphone" value="@if (old('telephone')) {{ old('telephone') }} @else {{$entreprise->telephone}} @endif" data-inputmask="'mask': '99-99-99-99-99'">
                  @error('telephone')
                      <span id="name-error" class="error invalid-feedback">{{$errors->first('telephone')}}</span>
                  @enderror
              </div>
            </div>
        </div>
      </div>
      <div class="card-footer">
        <button type="submit" class="btn btn-primary">Modifier l'entreprise</button>
      </div>
    </form>
    </div>

    @section('script')

    <script>

        $("#telephone").inputmask({"mask": "99-99-99-99-99"});
        $("#code_postal").inputmask({"mask": "99999"});

    </script>


    @endsection

@endsection

resources/views/entreprises/indexEntreprise.blade.php
@extends('layouts.template')
@section('title_page', 'Entreprises')
@section('content')
      <div class="card card-olive">
        <div class="card-header">
          <h3 class="card-title">Liste des entreprises</h3>
        </div>
        <div class="card-body">
            <table id="table" class="table table-bordered table-hover dataTable" role="grid">
            <thead>
                <tr role="row">
                    <th class="sorting_asc" tabindex="0" aria-controls="table" rowspan="1" colspan="1">Nom</th>
                    <th class="sorting" tabindex="0" aria-controls="table" rowspan="1" colspan="1">Adresse</th>
                    <th class="sorting" tabindex="0" aria-controls="table" rowspan="1" colspan="1">contact</th>
                    <th class="sorting" tabindex="0" aria-controls="table" rowspan="1" colspan="1">Addresse Email</th>
                    <th class="sorting" tabindex="0" aria-controls="table" rowspan="1" colspan="1">Téléphone</th>
                    <th class="sorting" tabindex="0" aria-controls="table" rowspan="1" colspan="1">Nombre d'offre</th>
                    <th class="sorting" tabindex="0" aria-controls="table" rowspan="1" colspan="1" style="text-align: right">Action</th>
                </tr>
            </thead>
            <tbody>
            @foreach ($entreprises as $entreprise)
                <tr role="row" class="odd">                
                    <td>{{$entreprise->nom}}</td>
                    <td>{{$entreprise->addresse." ".$entreprise->code_postal." ".$entreprise->ville}} </td>
                    <td>{{$entreprise->contact}}</td>
                    <td>{{$entreprise->email}}</td>
                    <td>{{$entreprise->telephone}}</td>
                    <td>{{$entreprise->offres->count()}}</td>
                    <td>
                        <div class="btn-group" style="display: block;text-align: right;">
                            <a href="{{route('entreprises.edit', $entreprise)}}"><button type="button" class="btn btn-primary"><i class="fas fa-edit"></i></button></a>
                        <button class="btn btn-danger remove-user" data-name="{{$entreprise->nom}}" data-action="{{ route('entreprises.destroy',$entreprise) }}"><i class="fas fa-trash"></i></button>
                        </div>
                    </td>
                </tr>
            @endforeach
            </tbody>
          </table>
        </div>
      </div>
      @section('script')

      <script>
$("body").on("click",".remove-user",function(){

var current_object = $(this);
var name = current_object.attr('data-name');

swal.fire({

    title: "Êtes vous sur ?",
    text: "Voulez-vous vraiment supprimer l'entreprise suivante : "+name+" ?",
    type: 'warning',
    showCancelButton: true,
    cancelButtonColor: '#6c757d',
    confirmButtonColor: '#dc3545',
    confirmButtonText: 'Supprimer !',
    reverseButtons: true

}).then((result) =>{

    if (result.value) {

        var action = current_object.attr('data-action');

        $('body').html("<form class='form-inline remove-form' method='post' action='"+action+"'></form>");
        $('body').find('.remove-form').append('@csrf');
        $('body').find('.remove-form').append('@method('DELETE')');
        $('body').find('.remove-form').submit();
    }

});

});

      </script>
          
      @endsection

@endsection