routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::view('/', 'auth.login');

Auth::routes(['register' => false]);

Route::get('home', 'HomeController@index')->name('home');

Route::resource('users', 'UsersController');

Route::resource('entreprises', 'EntreprisesController');

Route::resource('offres', 'OffresController');
Route::post('offres/download/{offre}', 'OffresController@download')->name('offres.download');

app/Models/Offre.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Offre extends Model
{
    protected $fillable = ['titre', 'description', 'niveau', 'pdf', 'id_entreprise'];

    protected $primaryKey = 'id_offre';

    public function entreprise()
    {
        return $this->belongsTo('App\Models\Entreprise', 'id_entreprise', 'id_entreprise');

    }
}

app/Http/Controllers/OffresController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Support\Facades\Storage;
use Illuminate\Http\Request;
use \App\Models\User;
use \App\Models\Offre;
use \App\Models\Entreprise;

class OffresController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('admin')->except(['show','index', 'download']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if (\Auth::user()->is_admin == true)
        {
            $offres = Offre::all();

            return view('offres.indexOffre', compact('offres'));
        }
        else
        {
            $offres = Offre::paginate(5);

            return view('offres.viewOffre', compact('offres'));
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $entreprises = Entreprise::all();

        return view('offres.createOffre', compact('entreprises'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    { 
        $offre = Offre::create($this->validateData());

        $this->storeFile($offre);

        return redirect()->route('offres.index')->withToastSuccess('Offre créée avec succès !!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Offre $offre)
    {
        return view('offres.showOffre', compact('offre'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Offre $offre)
    {
        $entreprises = Entreprise::all();
        return view('offres.editOffre', compact('offre', 'entreprises'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Offre $offre)
    {
        $offre->update($this->validateData());

        $this->storeFile($offre);

        return redirect()->route('offres.index')->withToastSuccess('Offre modifiée avec succès !!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Offre $offre)
    {
        $offre->delete();

        return redirect()->route('offres.index')->withToastSuccess('Offre supprimée avec succès !!');
    }

    public function download(Offre $offre)
    {
        if ($offre->pdf != null)
        {
            return Storage::download($offre->pdf);
        }
        else
        {
            return back()->withToastError('Pas de descriptif pour cette offre d\'emploi !!');
        }
        
    }

    private function storeFile(Offre $offre)
    {
        if(request('pdf'))
        {
            $offre->update([
                'pdf' => request()->file('pdf')->store('pdf')
            ]);
        }
    }

    private function validateData()
    {
        return \Validator::make(request()->all(), [
            'titre' => 'required|string|max:255',
            'description' => 'required|string|min:3',
            'niveau' => 'required|string|max:255',
            'pdf' => 'sometimes|mimes:pdf|max:2048',
            'id_entreprise' => 'required|integer',
        ])->validate();
    }

}

resources/views/offres/createOffre.blade.php
@extends('layouts.template')
@section('title_page', 'Créer une offre d\'emploi')
@section('content')

<div class="card card-primary">
    <div class="card-header">
      <h3 class="card-title">Créer une offre d'emploi</h3>
    </div>
    <form method="POST" action="{{route('offres.store') }}" enctype="multipart/form-data">
        @csrf
        @method('POST')
      <div class="card-body">
          <div class="row">
              <div class="col-sm-6">
                <div class="form-group">
                    <label for="nom">titre de l'offre d'emploi</label>
                    <input type="text" class="form-control @error('titre') is-invalid @enderror" id="titre" name="titre" placeholder="Entrer un titre pour l'offre d'emploi..." value="{{ old('titre') }}">
                    @error('titre')
                        <span id="name-error" class="error invalid-feedback">{{$errors->first('titre')}}</span>
                    @enderror
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                    <label for="email">Niveau d'étude</label>
                    <input type="text" class="form-control @error('niveau') is-invalid @enderror" id="niveau" name="niveau" placeholder="Entrer un niveau d'étude, un diplôme..." value="{{ old('niveau') }}">
                    @error('niveau')
                        <span id="name-error" class="error invalid-feedback">{{$errors->first('niveau')}}</span>
                    @enderror
                </div>
              </div>
          </div>
          <div class="row">
            <div class="col-md-6" data-select2-id="69">
                <div class="form-group" data-select2-id="68">
                  <label for="id_entreprise">Selectionner une entreprise</label>
                    <select class="form-control select2bs4 select2-hidden-accessible" style="width: 100%;" data-select2-id="17" tabindex="-1" aria-hidden="true" name="id_entreprise" id="id_entreprise">
                        @foreach($entreprises as $entreprise)
                        <option value="{{$entreprise->id_entreprise}}">{{$entreprise->nom}}</option>
                        @endforeach
                    </select>
                </div>
                <!-- /.form-group -->
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label for="pdf">Descriptif du poste en PDF (optionel)</label>
                  <div class="input-group">
                    <div class="custom-file" style="display: unset;">
                      <input type="file" class="custom-file-input @error('pdf') is-invalid @enderror" id="pdf" name="pdf">
                      <label class="custom-file-label" for="pdf">Choisir un fichier</label>
                      @error('pdf')
                      <span id="name-error" class="error invalid-feedback">{{$errors->first('pdf')}}</span>
                    @enderror
                    </div>
                  </div>
                </div>
              </div>
          </div>
          <div class="row">
                <label for="description">Description de l'offre d'emploi</label>
                 <textarea class="form-control @error('description') is-invalid @enderror" rows="3" placeholder="Entrer une description ..." name="description" id="description" value="{{ old('description') }}">{{old('description')}}</textarea>
                @error('description')
                    <span id="name-error" class="error invalid-feedback">{{$errors->first('description')}}</span>
                @enderror
          </div>
      </div>
      <div class="card-footer">
        <button type="submit" class="btn btn-primary">Créer l'offre d'emploi</button>
      </div>
    </form>
    </div>

@endsection

resources/views/offres/editOffre.blade.php
@extends('layouts.template')
@section('title_page', 'Modification une offre d\'emploi')
@section('content')

<div class="card card-primary">
    <div class="card-header">
      <h3 class="card-title">Modifier une offre d'emploi</h3>
    </div>
    <form method="POST" action="{{route('offres.update', $offre) }}" enctype="multipart/form-data">
        @csrf
        @method('PATCH')
      <div class="card-body">
          <div class="row">
              <div class="col-sm-6">
                <div class="form-group">
                    <label for="nom">titre de l'offre d'emploi</label>
                <input type="text" class="form-control @error('titre') is-invalid @enderror" id="titre" name="titre" placeholder="Entrer un titre pour l'offre d'emploi..." value="@if (old('titre')) {{old('titre') }} @else {{$offre->titre}} @endif">
                    @error('titre')
                        <span id="name-error" class="error invalid-feedback">{{$errors->first('titre')}}</span>
                    @enderror
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                    <label for="email">Niveau d'étude</label>
                    <input type="text" class="form-control @error('niveau') is-invalid @enderror" id="niveau" name="niveau" placeholder="Entrer un niveau d'étude, un diplôme..." value="@if (old('niveau')) {{old('niveau') }} @else {{$offre->niveau}} @endif">
                    @error('niveau')
                        <span id="name-error" class="error invalid-feedback">{{$errors->first('niveau')}}</span>
                    @enderror
                </div>
              </div>
          </div>
          <div class="row">
            <div class="col-md-6" data-select2-id="69">
                <div class="form-group" data-select2-id="68">
                  <label for="id_entreprise">Selectionner une entreprise</label>
                    <select class="form-control select2bs4 select2-hidden-accessible" style="width: 100%;" data-select2-id="17" tabindex="-1" aria-hidden="true" name="id_entreprise" id="id_entreprise">
                        @foreach($entreprises as $entreprise)
                        <option @if ($entreprise == $offre->entreprise) selected @endif value="{{$entreprise->id_entreprise}}">{{$entreprise->nom}}</option>
                        @endforeach
                    </select>
                </div>
                <!-- /.form-group -->
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <label for="pdf">Descriptif du poste en PDF (optionel)</label>
                  <div class="input-group">
                    <div class="custom-file" style="display: unset;">
                      <input type="file" class="custom-file-input @error('pdf') is-invalid @enderror" id="pdf" name="pdf">
                      <label class="custom-file-label" for="pdf">Choisir un fichier</label>
                      @error('pdf')
                      <span id="name-error" class="error invalid-feedback">{{$errors->first('pdf')}}</span>
                    @enderror
                    </div>
                  </div>
                </div>
              </div>
          </div>
          <div class="row">
                <label for="description">Description de l'offre d'emploi</label>
                 <textarea class="form-control @error('description') is-invalid @enderror" rows="3" placeholder="Entrer une description ..." name="description" id="description" value="{{ old('description') }}">@if (old('description')) {{old('description') }} @else {{$offre->description}} @endif</textarea>
                @error('description')
                    <span id="name-error" class="error invalid-feedback">{{$errors->first('description')}}</span>
                @enderror
          </div>
      </div>
      <div class="card-footer">
        <button type="submit" class="btn btn-primary">Modifier l'offre d'emploi</button>
      </div>
    </form>
    </div>

@endsection

resources/views/offres/indexOffre.blade.php
@extends('layouts.template')
@section('title_page', 'Liste des offres d\'emploi')
@section('content')
      <div class="card card-lightblue">
        <div class="card-header">
          <h3 class="card-title">Liste des offres d'emploi</h3>
        </div>
        <div class="card-body">
            <table id="table" class="table table-bordered table-hover dataTable" role="grid">
            <thead>
                <tr role="row">
                    <th class="sorting_asc" tabindex="0" aria-controls="table" rowspan="1" colspan="1">Titre</th>
                    <th class="sorting" tabindex="0" aria-controls="table" rowspan="1" colspan="1">Descritpion</th>
                    <th class="sorting" tabindex="0" aria-controls="table" rowspan="1" colspan="1">niveau</th>
                    <th class="sorting" tabindex="0" aria-controls="table" rowspan="1" colspan="1">Entreprise</th>
                    <th class="sorting" tabindex="0" aria-controls="table" rowspan="1" colspan="1" style="text-align: right">Action</th>
                </tr>
            </thead>
            <tbody>
            @foreach ($offres as $offre)
                <tr role="row" class="odd">                
                    <td>{{$offre->titre}}</td>
                    <td>{{substr($offre->description, 0, 50)."..."}} </td>
                    <td>{{$offre->niveau}}</td>
                    <td>{{$offre->entreprise->nom}}</td>
                    <td>
                        <div class="btn-group" style="display: block;text-align: right;">
                            <form method="POST" action="{{route('offres.download', $offre)}}">
                            @csrf
                            @method('POST')
                            <button type="submit" class="btn btn-success"><i class="fas fa-file-download"></i></button>
                            </form>
                            <a href="{{route('offres.edit', $offre)}}"><button type="button" class="btn btn-primary"><i class="fas fa-edit"></i></button></a>
                        <button class="btn btn-danger remove-user" data-name="{{$offre->titre}}" data-action="{{ route('offres.destroy',$offre) }}"><i class="fas fa-trash"></i></button>
                        </div>
                    </td>
                </tr>
            @endforeach
            </tbody>
          </table>
        </div>
      </div>
      @section('script')

      <script>
$("body").on("click",".remove-user",function(){

var current_object = $(this);
var name = current_object.attr('data-name');

swal.fire({

    title: "Êtes vous sur ?",
    text: "Voulez-vous vraiment supprimer l'offre d'emploi suivante : "+name+" ?",
    type: 'warning',
    showCancelButton: true,
    cancelButtonColor: '#6c757d',
    confirmButtonColor: '#dc3545',
    confirmButtonText: 'Supprimer !',
    reverseButtons: true

}).then((result) =>{

    if (result.value) {

        var action = current_object.attr('data-action');

        $('body').html("<form class='form-inline remove-form' method='post' action='"+action+"'></form>");
        $('body').find('.remove-form').append('@csrf');
        $('body').find('.remove-form').append('@method('DELETE')');
        $('body').find('.remove-form').submit();
    }

});

});

      </script>
          
      @endsection

@endsection

resources/views/offres/showOffre.blade.php
@extends('layouts.template')
@section('title_page', 'Offre d\'emploi N°'.$offre->id_offre)
@section('content')
<div class="invoice p-3 mb-3">
  <div class="row">
    <div class="col-12">
      <h1 class="text-primary" style="text-align: center;">{{$offre->titre}}</h1>
    </div>
  </div>
  <div class="row invoice-info" style="margin: 10px; margin-top: 20px;">
    <div class="col-sm-4 invoice-col">
      <h5><i class="fas fa-map-marker-alt fa-lg" style="margin: 10px;" ></i> {{$offre->entreprise->code_postal." ".$offre->entreprise->ville}}</h5>
      <h5><i class="fas fa-building fa-lg" style="margin: 10px;" ></i> {{$offre->entreprise->nom}}</h5>
    </div>
    <div class="col-sm-4 invoice-col">
      <h5><i class="fas fa-address-book fa-lg" style="margin: 10px;" ></i> {{$offre->entreprise->contact}}</h5>
      <h5><i class="fas fa-envelope fa-lg" style="margin: 10px;" ></i> {{$offre->entreprise->email}}</h5>
    </div>
    <div class="col-sm-4 invoice-col">
      <h5><i class="fas fa-phone fa-lg" style="margin: 10px;" ></i> {{$offre->entreprise->telephone}}</h5>
      <h5><i class="fas fa-graduation-cap fa-lg" style="margin: 10px;" ></i> {{$offre->niveau}}</h5>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
      <h5 class="text-primary" style="margin: 10px;margin-top: 20px;">Description du poste :</h5>
      <h6> {{$offre->description}}</h6>
    </div>
  </div>
  <div class="row">
    <div class="col-12" style="display: block ruby;">
      <h5 class="text-primary" style="margin-top: 20px;margin-right: 10px;">Déscriptif du poste :</h5>
      @if ($offre->pdf != null)
      <form method="POST" action="{{route('offres.download', $offre)}}">
        @csrf
        @method('POST')
        <button type="submit" class="btn btn-block bg-gradient-success btn-sm"><i class="fas fa-file-download" style="margin-right: 5px;"></i>Télécharger le descriptif </button>
      </form>
      @else
      <h6><strong> Pas de descriptif de poste joint a cette annonce</strong></h6>
      @endif
    </div>
  </div>       
  <div class="row">
    <div class="col-3">
      <h5 class="text-primary" style="margin-top: 20px;">Addresse de l'entreprise  :</h5>
      <h6> {{$offre->entreprise->addresse." ".$offre->entreprise->code_postal." ".$offre->entreprise->ville}} </h6>
    </div>
    <div class="col-9">
      <iframe style="margin-top: 20px;" width="100%" height="450" frameborder="0" style="border:0"src="https://www.google.com/maps/embed/v1/place?key=AIzaSyALxB0jNB59URaD5sPYLwi0bqyUDyOVjqA&q={{str_replace(" ","+",$offre->entreprise->addresse)."+".$offre->entreprise->code_postal."+".str_replace(" ","+",$offre->entreprise->ville)}}" allowfullscreen ></iframe>
    </div>
  </div>                
</div>



@endsection

resources/views/offres/viewOffre.blade.php
@extends('layouts.template')
@section('title_page', 'Les offres d\'emploi')
@section('content')
@foreach($offres as $offre)
<div class="card card-navy card-outline">
    <div class="card-header">
      <h3 class="card-title">
        <a href="{{route('offres.show', $offre->id_offre)}}">{{$offre->titre}}</a>
      </h3>
    </div>
    <div class="card-body">
        <div class="col-12">
            <strong>
                <p class="text-primary" style="display: inline;">Localisation : </p>
            </strong>
            {{$offre->entreprise->code_postal." ".$offre->entreprise->ville}}
        </div>
        <div class="col-12">
            <strong>
                <p class="text-primary" style="display: inline;">Entreprise : </p>
            </strong> 
            {{$offre->entreprise->nom}}
        </div>
        <div class="col-12">
        <strong>
            <p class="text-primary">Description du poste :</p>
        </strong>
        </div>
        {{substr($offre->description, 0, 300)."..."}} <a href="{{route('offres.show', $offre)}}">voir plus</a>
    </div>
    <!-- /.card-body -->
  </div>
  @endforeach

  <div class="row d-flex justify-content-center">
    {{$offres->links()}}
  </div>
  
@endsection